display:
  default:
    display_title: Mestre
    display_options:
      exposed_form:
        options:
          submit_button: Aplica
          reset_button_label: Reinicialitza
          exposed_sorts_label: 'Ordena per'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        quantity:
          separator: ', '
        purchased_entity:
          separator: ', '
        total_price__number:
          separator: ', '
      arguments:
        order_id:
          exception:
            title: Tot
